export const data = [
  { img: "/img/Bitmap1.png", category: "Design", title: "SOFA" },
  { img: "/img/Bitmap2.png", category: "Branding", title: "KeyBoard" },
  { img: "/img/Bitmap3.png", category: "Illustration", title: "Work Media" },
  { img: "/img/Bitmap4.png", category: "Motion", title: "DDDone" },
  { img: "/img/Bitmap5.png", category: "Design", title: "Abstract" },
  { img: "/img/Bitmap6.png", category: "Branding", title: "HandP" },
  { img: "/img/Bitmap7.png", category: "Motion", title: "Architect" },
  { img: "/img/Bitmap8.png", category: "Design", title: "CalC" },
  { img: "/img/Bitmap9.png", category: "Branding", title: "Sport" },
  { img: "/img/Bitmap1.png", category: "Design", title: "SOFA2" },
  { img: "/img/Bitmap2.png", category: "Branding", title: "KeyBoard2" },
  { img: "/img/Bitmap3.png", category: "Illustration", title: "Work Media2" },
  { img: "/img/Bitmap4.png", category: "Motion", title: "DDDone2" },
  { img: "/img/Bitmap5.png", category: "Design", title: "Abstract2" },
  { img: "/img/Bitmap6.png", category: "Branding", title: "HandP2" },
  { img: "/img/Bitmap7.png", category: "Motion", title: "Architect2" },
  { img: "/img/Bitmap8.png", category: "Design", title: "CalC2" },
  { img: "/img/Bitmap9.png", category: "Branding", title: "Sport2" },
];
